// https://www.easyhindityping.com/marathi-alphabet

export const marathiAlphabet = [
  { marathi: 'अ', latin: 'a', difficulty: 1 },
  { marathi: 'आ', latin: 'ā', difficulty: 2 },
  { marathi: 'इ', latin: 'i', difficulty: 1 },
  { marathi: 'ई', latin: 'ī', difficulty: 2 },
  { marathi: 'उ', latin: 'u', difficulty: 1 },
  { marathi: 'ऊ', latin: 'ū', difficulty: 2 },
  { marathi: 'ए', latin: 'e', difficulty: 1 },
  { marathi: 'ऐ', latin: 'ai', difficulty: 2 },
  { marathi: 'ओ', latin: 'o', difficulty: 1 },
  { marathi: 'औ', latin: 'au', difficulty: 3 },
  { marathi: 'क', latin: 'ka', difficulty: 1 },
  { marathi: 'ख', latin: 'kha', difficulty: 2 },
  { marathi: 'ग', latin: 'ga', difficulty: 1 },
  { marathi: 'घ', latin: 'gha', difficulty: 2 },
  { marathi: 'च', latin: 'ca', difficulty: 1 },
  { marathi: 'छ', latin: 'cha', difficulty: 2 },
  { marathi: 'ज', latin: 'ja', difficulty: 1 },
  { marathi: 'झ', latin: 'jha', difficulty: 3 },
  { marathi: 'ट', latin: 'ṭa', difficulty: 2 },
  { marathi: 'ठ', latin: 'ṭha', difficulty: 3 },
  { marathi: 'ड', latin: 'ḍa', difficulty: 2 },
  { marathi: 'ढ', latin: 'ḍha', difficulty: 3 },
  { marathi: 'ण', latin: 'ṇa', difficulty: 3 },
  { marathi: 'त', latin: 'ta', difficulty: 1 },
  { marathi: 'थ', latin: 'tha', difficulty: 2 },
  { marathi: 'द', latin: 'da', difficulty: 1 },
  { marathi: 'ध', latin: 'dha', difficulty: 2 },
  { marathi: 'न', latin: 'na', difficulty: 1 },
  { marathi: 'प', latin: 'pa', difficulty: 1 },
  { marathi: 'फ', latin: 'pha', difficulty: 2 },
  { marathi: 'ब', latin: 'b', difficulty: 2 },
  { marathi: 'भ', latin: 'bha', difficulty: 2 },
  { marathi: 'म', latin: 'ma', difficulty: 1 },
  { marathi: 'य', latin: 'ya', difficulty: 1 },
  { marathi: 'र', latin: 'ra', difficulty: 1 },
  { marathi: 'ल', latin: 'la', difficulty: 1 },
  { marathi: 'व', latin: 'v', difficulty: 1 },
  { marathi: 'श', latin: 'śa', difficulty: 2 },
  { marathi: 'ष', latin: 'ṣa', difficulty: 2 },
  { marathi: 'स', latin: 'sa', difficulty: 1 },
  { marathi: 'ह', latin: 'h', difficulty: 1 },
  { marathi: 'ळ', latin: 'ḷa', difficulty: 2 },
  { marathi: 'क्ष', latin: 'kṣa', difficulty: 3 },
  { marathi: 'ज्ञ', latin: 'jña', difficulty: 3 },
];

export const marathiNumbers = [
  { marathi: '०', latin: '0', difficulty: 1 },
  { marathi: '१', latin: '1', difficulty: 1 },
  { marathi: '२', latin: '2', difficulty: 1 },
  { marathi: '३', latin: '3', difficulty: 1 },
  { marathi: '४', latin: '4', difficulty: 1 },
  { marathi: '५', latin: '5', difficulty: 1 },
  { marathi: '६', latin: '6', difficulty: 1 },
  { marathi: '७', latin: '7', difficulty: 1 },
  { marathi: '८', latin: '8', difficulty: 1 },
  { marathi: '९', latin: '9', difficulty: 1 },
];
